{% set version = "0.2.2" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-ocedata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ocedata_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ocedata/ocedata_{{ version }}.tar.gz
  sha256: f3c71bc6797dc3b6d858d1082385e7e9eba2fe107f8bd846690633a5d403497a

build:
  number: 3

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-testthat

  run:
    - r-base
    - r-testthat

test:
  commands:
    - $R -e "library('ocedata')"           # [not win]
    - "\"%R%\" -e \"library('ocedata')\""  # [win]

about:
  home: https://dankelley.github.io/ocedata

  license: GPL-2.0-or-later
  summary: Several Oceanographic data sets are provided for use by the 'oce' package and for other purposes.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - ocefpaf
